# Describes the format for available hwam_stove services

set_clock:
  description: Set the clock on the HWAM stove.
  fields:
    stove_name:
      description: The stove name as specified in configuration.yaml.
    date:
      description: Optional date to set on the stove. Defaults to today.
      example: '2018-10-23'
    time:
      description: Optional time in 24h format to set on the stove. Defaults to the current time.
      example: '19:34'
